### ISSUE TITLE
io.circe.yaml.parse is not threadsafe

### ISSUE THREAD

**Issue by jwiklund** [circe/circe-yaml#112]
[yamlToJson](https://github.com/circe/circe-yaml/blob/master/src/main/scala/io/circe/yaml/parser/package.scala#L20) uses a shared [flattener](https://github.com/circe/circe-yaml/blob/master/src/main/scala/io/circe/yaml/parser/package.scala#L51) ([here](https://github.com/circe/circe-yaml/blob/master/src/main/scala/io/circe/yaml/parser/package.scala#L93)) which extends [SafeConstructor](https://bitbucket.org/asomov/snakeyaml/src/3d49667ece57d564668b9a155c55ccfe26aaca00/src/main/java/org/yaml/snakeyaml/constructor/SafeConstructor.java#lines-46) which extends [BaseConstructor](https://bitbucket.org/asomov/snakeyaml/src/3d49667ece57d564668b9a155c55ccfe26aaca00/src/main/java/org/yaml/snakeyaml/constructor/BaseConstructor.java#lines-51) which contains a [map of constructed objets](https://bitbucket.org/asomov/snakeyaml/src/3d49667ece57d564668b9a155c55ccfe26aaca00/src/main/java/org/yaml/snakeyaml/constructor/BaseConstructor.java#lines-227) which is not thread safe.

**Comment by travisbrown** [comment]
Fixed in #114, published as [0.13.1](https://github.com/circe/circe-yaml/releases/tag/v0.13.1).
