### ISSUE TITLE
Support maxAliasesForCollections override

### ISSUE THREAD

**Issue by hcdeng** [circe/circe-yaml#136]
SnakeYaml defaults "maxAliasesForCollections" to 50, and supports overriding this value via https://www.javadoc.io/doc/org.yaml/snakeyaml/latest/org/yaml/snakeyaml/LoaderOptions.html. This would probably be implemented the same way as https://github.com/circe/circe-yaml/issues/120.

We have a project that parses yml files with more than 50 aliases - currently using a workaround for this.

**Comment by hcdeng** [comment]
Starting work on this

**Comment by ajj-stripe** [comment]
Would very much appreciate if you could implement https://github.com/circe/circe-yaml/issues/120 at the same time, but totally understand if it requires significant extra effort

**Comment by hcdeng** [comment]
Doesn't seem like too much work, but [the PR for maxAliasesForCollections](https://github.com/circe/circe-yaml/pull/205) is (hopefully) only a couple button clicks away from getting merged. Once it's in, adding https://github.com/circe/circe-yaml/issues/120 should be pretty small/straightforward. If it happens in the next couple of weeks, I should have time to tackle it.

**Comment by jeffmay** [comment]
This is resolved by https://github.com/circe/circe-yaml/releases/tag/v0.14.2
