### ISSUE TITLE
0.4.0 Not Published For Scala 2.12 (seems to be an accident)

### ISSUE THREAD

**Issue by clhodapp** [circe/circe-yaml#17]
For some reason the final 0.4.0 artifact for Scala 2.12 is not in maven central. From what I can see, prerelease snaphshots were published, so this seems to just be an oversight.

**Comment by amrhassan** [comment]
Any chance of getting this soon?

**Comment by travisbrown** [comment]
I've just opened #18 with an overhaul for the build config and will publish 0.5.0 for all three Scala versions later today if there are no objections.

**Comment by jeremyrsmith** [comment]
Closing since @travisbrown released 0.5.0 with Scala 2.12 supported.
