### ISSUE TITLE
0.14 release?

### ISSUE THREAD

**Issue by mpilquist** [circe/circe-yaml#214]
Any ETA on a 0.14 release? Thanks!

**Comment by gbielskiqt** [comment]
Hey, @travisbrown, can we expect the 0.14 release of `circe-yaml` any time soon? 🙏 
Thanks in advance!

**Comment by travisbrown** [comment]
Done, and apologies for the delay (although note that the 0.13.1 release should work with Circe 0.14.x with no issues beyond eviction warnings): https://github.com/circe/circe-yaml/releases/tag/v0.14.0
