### ISSUE TITLE
Make a new release (or setup sbt-ci-release)

### ISSUE THREAD

**Issue by sideeffffect** [circe/circe-yaml#344]
Hello,
can we please make a new release?
I've cut https://github.com/circe/circe-yaml/releases/tag/v0.14.3-RC1 but there's no GitHub Action setup to make a release.

Or even better, set up https://github.com/sbt/sbt-ci-release/ . That way the release process will be automated.

/cc @zarthross @zmccoy @jeffmay

**Comment by zarthross** [comment]
@sideeffffect You can now publish by creating a github-release.  Snapshots are also being published, see https://github.com/circe/circe-yaml/actions/runs/3501271262/jobs/5864924937

**Comment by sideeffffect** [comment]
Awesome, thanks! :heart:

**Comment by sideeffffect** [comment]
https://github.com/circe/circe-yaml/releases/tag/v0.14.3-RC2
