### ISSUE TITLE
Please support automatic case class decoding with default values

### ISSUE THREAD

**Issue by tinder-michaelallman** [circe/circe-yaml#88]
Hello. Suppose I have a case class like

```
Duh(hello: String, world: String = "World")
```

and I want to use the super automagic generic programming technique for magically decoding yaml to an instance of `Duh` when my yaml file looks like:

```
hello: hello
```

Right now this doesn't work because it complains that there's no `world` field in the file. But I want it to use the default `World` string provided in the constructor when there's no `world` field.

I hope this is easy. Otherwise everyone is going to be mad at me for wasting half a day trying to make our code better instead of broken.

Thank you.

**Comment by jeremyrsmith** [comment]
Hi,

This is something that happens at the circe level rather than circe-yaml. You need `circe-generic-extras`, and you'd configure it like this:

```scala
implicit val circeConfig: Configuration = Configuration.default.withDefaults
```

See https://github.com/circe/circe-generic-extras for more info about this.

**Comment by tinder-michaelallman** [comment]
> Hi,
> 
> This is something that happens at the circe level rather than circe-yaml. You need `circe-generic-extras`, and you'd configure it like this:
> 
> ```scala
> implicit val circeConfig: Configuration = Configuration.default.withDefaults
> ```
> 
> See https://github.com/circe/circe-generic-extras for more info about this.

Thank you, Jeremy. This works perfectly.
