### ISSUE TITLE
printer.print is verbose

### ISSUE THREAD

**Issue by jeffmay** [circe/circe-yaml#9]
```scala
scala> io.circe.yaml.printer.print(io.circe.Json.fromInt(1))
res1: String =
"%YAML 1.1
--- 1
"
```

It would be nice if we separated `print` from `printDocument` and print would just be a minimal printer, similar to Json's default printer.

**Comment by jeremyrsmith** [comment]
@jeffmay This is fixed in the latest master - using `Auto` as the default version tells it to leave out the version tag.
